<?php

const BLOCK_FORUM_REPORT_STATUS_SCHEDULED = 0;
const BLOCK_FORUM_REPORT_STATUS_EXECUTING = 1;
const BLOCK_FORUM_REPORT_STATUS_ERROR = 2;
const BLOCK_FORUM_REPORT_STATUS_FINISH = 3;
const BLOCK_FORUM_REPORT_STATUS_DELETED = 4;
